- .idea/misc.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/SpikeCodeDetector.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/SpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CVMaster.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Extendo.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/FlippingIntake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Hopper.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFLimitSwitch.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/Queuer.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/AprilTagRRTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/RFThreeTrackingWheelLocalizer.kt
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/StandardTrackingWheelLocalizer.java
> Second part of Skeleton

- .idea/misc.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/FutureComponents/Extendo.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/FutureComponents/FlippingIntake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Hopper.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Intake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Launcher.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BasicRobot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/AprilTagRRTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/StandardTrackingWheelLocalizer.java
Launcher & Intake added, Extendo and FlippingIntake moved to future storage
> Accomodating for change in HW plans

- .idea/misc.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/ArmTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFServoTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFUltrasonicTest.java
Created skeleton for Lift, RFServoTest, and ArmTest
> First part of skeleton

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Hopper.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFColorSensor.java
> Harrie arm hopper colorsensor filled

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CVMaster.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Hopper.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Intake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Launcher.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/Logger.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/Queuer.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/RFLogger.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BasicRobot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TeleOp/CSTeleOp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/AprilTagRRTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/IMUTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/StandardTrackingWheelLocalizer.java
> April tag done?? TeleOp in!

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/RFLogger.java
> RFLogger hopefully final version

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/FlippingIntake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Intake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFBreakBeam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFDualServo.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFUltrasonic.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Ultrasonics.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFDualServoTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFServoTest.java
late because of some conflicts
> full skeleton draft

- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CVMaster.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/RFLogger.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
> Autonomous

- .idea/misc.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- build.common.gradle
> WilliamWorking

- .idea/misc.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CVMaster.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Launcher.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
> Fixed logging for some classes

- .idea/misc.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFColorSensor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFColorSensorTest.java
- gradle/wrapper/gradle-wrapper.properties
> rfccolorsensor

- .idea/misc.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/BlueSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RedSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CVMaster.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Intake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Launcher.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFDualMotor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFGamepad.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFMotionProfile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFMotor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/Queuer.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/RFLogger.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Wrist.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BasicRobot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/AutoRFMotorTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFMotorAutoTuneTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFMotorTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/TesMotorTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/DriveConstants.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
- build.dependencies.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> RfMotor done and new state machine restrictions

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Clamp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Wrist.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/ArmTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFServoTest.java
> servo testing more

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Intake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFMotionProfile.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFMotor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Wrist.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/ArmTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/AutoRFMotorTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFMotorAutoTuneTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/TesMotorTest.java
> Progress on teleOp

- .idea/misc.xml
- TeamCode/build.gradle
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Intake.java
- gradle.properties
> intak e tune

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Clamp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/ClampTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/PreloadTest.java
> tests programs

- .idea/misc.xml
- TeamCode/build.gradle
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Wrist.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/ArmTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/BradapultTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/ClampTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/PreloadTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFServoTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/wristTest.java
> Servo positions all configed

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFServo.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Wrist.java
> arm work done

- .idea/misc.xml
- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/BlueLeftAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/BlueRightAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedRightAuto.java
> PR For hyun redleftauto stuff

- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/BlueLeftAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/BlueRightAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAuto.java
> fixed autos, the previous branch ahd the wrong auton code

- .idea/misc.xml
- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/BlueSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RedSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CVMaster.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Clamp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Intake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Launcher.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Preloader.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFDualMotor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFDualServo.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFMotor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFServo.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/QueueElement.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/RFLogger.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Wrist.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFMotorTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/TesMotorTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/StandardTrackingWheelLocalizer.java
> WarrenWorking

- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting2.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/BlueRightAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAuto.java
> bleu right mepped

- .idea/misc.xml
- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedRightAuto.java
> redleftautoPRbranch

- .idea/misc.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Clamp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Intake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
> Clamp position and some other teleOp Stuff

- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedRightPark.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RedSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CVMaster.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Clamp.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Hanger.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Intake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Launcher.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Preloader.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFDualMotor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFMotor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFServo.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/Queuer.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Wrist.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/TesMotorTest.java
> teleop fixes and auto fixes

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedRightAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
> red left park spike position 0 and 2

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedRightAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/BlueSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RedSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CVMaster.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- build.dependencies.gradle
- build.gradle
- gradle.properties
> Auto, 8.1.3, apriltag

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/BlueSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RedSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Hanger.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Launcher.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFMotor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Wrist.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
> auto and teleOp fixed

- .idea/misc.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/BlueLeftAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/BlueRightAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedRightAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/BlueRightSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/BlueSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RedRightSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CVMaster.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Hanger.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Intake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Wrist.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
> auto fixes

- .idea/misc.xml
- FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/internal/FtcRobotControllerActivity.java
- FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/internal/PermissionValidatorWrapper.java
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> gradle 8.5~

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFLocalizerTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RoadRunMoveTest2.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/DriveConstants.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/StandardTrackingWheelLocalizer.java
> prep for new code

- FtcRobotController/src/main/AndroidManifest.xml
- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting2.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RedLeftPathTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/DriveConstants.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/StandardTrackingWheelLocalizer.java
> new version for code, trying to test odom at high speed

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/CSAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CVMaster.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BasicRobot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/AprilTagRRTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/KotlinAprilTagRRTest.kt
- build.dependencies.gradle
> bulk caching manual + c920

- TeamCode/build.gradle
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFDualMotor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/AprilTagRRTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/PPpoof.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RedLeftPathTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/DriveConstants.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
- build.common.gradle
- build.dependencies.gradle
> Ftclib pure pursuit implemented and integrated with ququer+ c920 at 800 x 600 + sqpnp

- .idea/misc.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/DriveConstants.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/StandardTrackingWheelLocalizer.java
> new roadrun constants

- .idea/misc.xml
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/KotlinAprilTagRRTest.kt
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RedLeftPathTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/DriveConstants.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/PoseStorage.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/RFThreeTrackingWheelLocalizer.kt
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/StandardTrackingWheelLocalizer.java
- build.dependencies.gradle
> apriltag + pure pursuid!

- FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/UtilityCameraFrameCapture.java
- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Arm.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/BlueSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFVisionPortal.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFVisionPortalImpl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RedSpikeObserverPipeline.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CVMaster.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Claw.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Magazine.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/System/RFLogger.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Twrist.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Wrist.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BasicRobot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RedLeftPathTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/DriveConstants.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/PoseStorage.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/RFThreeTrackingWheelLocalizer.kt
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/StandardTrackingWheelLocalizer.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/BackAndForth.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/opmode/ManualFeedforwardTuner.java
> Minor fixes

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Claw.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Intake.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Lift.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Preloader.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFDualMotor.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFServoTest.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/DriveConstants.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/SampleMecanumDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/StandardTrackingWheelLocalizer.java
> new chassis stuff

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeft20.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAut.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedLeftAutCycle.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RedRightAut.java
> red left in progress

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Magazine.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
> colorsensorleds

- MeepMeepTesting/src/main/java/com/example/meepmeeptesting/MeepMeepTesting.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RLRR.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/CV/Pipelines/RFAprilCam.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Magazine.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/drive/DriveConstants.java
> RLRR and some changes

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/BL20.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/BL21.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RL20.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Autonomous/RL21.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/Line.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/RFModules/Devices/RFUltrasonic.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Components/Ultrasonics.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robots/BradBot.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Tests/RFUltrasonicTest.java
> uldersanik
